// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzb2QrAai3944u93-MV6GYbDoif1taEeE',
    appId: '1:665054180024:web:19c02e4d9a7750fb307a4d',
    messagingSenderId: '665054180024',
    projectId: 'webrtc-flutter-50377',
    authDomain: 'webrtc-flutter-50377.firebaseapp.com',
    databaseURL: 'https://webrtc-flutter-50377-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webrtc-flutter-50377.appspot.com',
    measurementId: 'G-SWEJ73QKTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZP4ABjMWRDc5vXmz0tZzgSzkoE0yc5k',
    appId: '1:665054180024:android:d4c237b6b254073b307a4d',
    messagingSenderId: '665054180024',
    projectId: 'webrtc-flutter-50377',
    databaseURL: 'https://webrtc-flutter-50377-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webrtc-flutter-50377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtBJyfcig4AVLQGvI3G9PTA9n7uSRNkVY',
    appId: '1:665054180024:ios:4fed7a5714d6b540307a4d',
    messagingSenderId: '665054180024',
    projectId: 'webrtc-flutter-50377',
    databaseURL: 'https://webrtc-flutter-50377-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webrtc-flutter-50377.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtBJyfcig4AVLQGvI3G9PTA9n7uSRNkVY',
    appId: '1:665054180024:ios:f1b7170ba533cf33307a4d',
    messagingSenderId: '665054180024',
    projectId: 'webrtc-flutter-50377',
    databaseURL: 'https://webrtc-flutter-50377-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webrtc-flutter-50377.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtcTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzb2QrAai3944u93-MV6GYbDoif1taEeE',
    appId: '1:665054180024:web:bb2ea65233e24bd4307a4d',
    messagingSenderId: '665054180024',
    projectId: 'webrtc-flutter-50377',
    authDomain: 'webrtc-flutter-50377.firebaseapp.com',
    databaseURL: 'https://webrtc-flutter-50377-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webrtc-flutter-50377.appspot.com',
    measurementId: 'G-VWK0LFJ3FV',
  );

}